language: python

dist: trusty

sudo: false

matrix:
  include:
    env: ELASTICVERSION=1.7
    addons:
      apt:
        sources:
          - elasticsearch-$ELASTICVERSION
        packages:
          - elasticsearch

services:
  - elasticsearch

install:
  - pip install -U pip tox

before_script:
  - sleep 10

script:
  - cd tests && tox
